import type { HsAnalysis } from './supabase'

export function generateReportText(analysis: HsAnalysis): string {
  const candidate = analysis.candidate_name?.trim() || 'Anonymous'
  const role = analysis.role_title
  const date = new Date(analysis.created_at).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  const matchedSkills = analysis.matched_skills.join(', ') || 'None identified'
  const missingSkills = analysis.missing_skills.join(', ') || 'None identified'
  const keywordGaps = analysis.keyword_gaps.join(', ') || 'None identified'

  const strengthsList = analysis.strengths
    .map((s, i) => `  ${i + 1}. ${s}`)
    .join('\n')

  const weaknessesList = analysis.weaknesses
    .map((w, i) => `  ${i + 1}. ${w}`)
    .join('\n')

  const bulletRewrites = analysis.bullet_rewrites
    .map(
      (b, i) => `
  Rewrite ${i + 1}:
  Original:  ${b.original}
  Improved:  ${b.rewritten}
  Reason:    ${b.reason}`
    )
    .join('\n')

  return `
════════════════════════════════════════════════════════
  HIRESIGNAL ANALYSIS REPORT
════════════════════════════════════════════════════════

  Candidate:    ${candidate}
  Role:         ${role}
  Date:         ${date}

────────────────────────────────────────────────────────
  MATCH OVERVIEW
────────────────────────────────────────────────────────

  MATCH SCORE:     ${analysis.match_score}%
  RECOMMENDATION:  ${analysis.recommendation.toUpperCase()}

  ${analysis.recommendation_reason}

────────────────────────────────────────────────────────
  SKILLS ANALYSIS
────────────────────────────────────────────────────────

  MATCHED SKILLS:
  ${matchedSkills}

  MISSING SKILLS:
  ${missingSkills}

  KEYWORD GAPS:
  ${keywordGaps}

────────────────────────────────────────────────────────
  CANDIDATE PROFILE
────────────────────────────────────────────────────────

  STRENGTHS:
${strengthsList}

  AREAS FOR IMPROVEMENT:
${weaknessesList}

────────────────────────────────────────────────────────
  RESUME IMPROVEMENTS
────────────────────────────────────────────────────────
${bulletRewrites}

════════════════════════════════════════════════════════
  Generated by HireSignal — AI Recruitment Intelligence
  Built by Abrar Tajwar Khan
════════════════════════════════════════════════════════
`.trim()
}

export function getReportFilename(analysis: HsAnalysis): string {
  const candidate = (analysis.candidate_name || 'anonymous')
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, '')

  const role = analysis.role_title
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
    .slice(0, 30)

  const date = new Date(analysis.created_at).toISOString().slice(0, 10)

  return `hiresignal-${candidate}-${role}-${date}.txt`
}
