import type { HsAnalysis } from './supabase'

export function generateReportText(analysis: HsAnalysis): string {
  const candidate = analysis.candidate_name?.trim() || 'Anonymous'
  const role = analysis.role_title
  const company = 'Unknown' // company is not stored on the analysis record directly
  const date = new Date(analysis.created_at).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  const matchedSkills = analysis.matched_skills.length
    ? analysis.matched_skills.join(', ')
    : 'None identified'
  const missingSkills = analysis.missing_skills.length
    ? analysis.missing_skills.join(', ')
    : 'None identified'
  const keywordGaps = analysis.keyword_gaps.length
    ? analysis.keyword_gaps.join(', ')
    : 'None identified'

  const strengthsList = analysis.strengths
    .map((s, i) => `  ${i + 1}. ${s}`)
    .join('\n')

  const weaknessesList = analysis.weaknesses
    .map((w, i) => `  ${i + 1}. ${w}`)
    .join('\n')

  const bulletRewrites = analysis.bullet_rewrites
    .map(
      (b, i) =>
        `  --- Rewrite ${i + 1} ---\n  Original: ${b.original}\n  Improved: ${b.rewritten}\n  Why: ${b.reason}`
    )
    .join('\n\n')

  return [
    '════════════════════════════════════════════════════════',
    '  HireSignal Analysis Report',
    '════════════════════════════════════════════════════════',
    '',
    `  Candidate:      ${candidate}`,
    `  Role:           ${role} at ${company}`,
    `  Date:           ${date}`,
    '',
    '────────────────────────────────────────────────────────',
    '',
    `  MATCH SCORE:       ${analysis.match_score}%`,
    `  RECOMMENDATION:    ${analysis.recommendation.toUpperCase()}`,
    '',
    '────────────────────────────────────────────────────────',
    '',
    '  MATCHED SKILLS:',
    `  ${matchedSkills}`,
    '',
    '  MISSING SKILLS:',
    `  ${missingSkills}`,
    '',
    '  KEYWORD GAPS:',
    `  ${keywordGaps}`,
    '',
    '────────────────────────────────────────────────────────',
    '',
    '  STRENGTHS:',
    strengthsList,
    '',
    '  AREAS FOR IMPROVEMENT:',
    weaknessesList,
    '',
    '────────────────────────────────────────────────────────',
    '',
    '  RESUME IMPROVEMENTS:',
    '',
    bulletRewrites,
    '',
    '────────────────────────────────────────────────────────',
    '',
    '  REASONING:',
    `  ${analysis.recommendation_reason}`,
    '',
    '════════════════════════════════════════════════════════',
    '  Generated by HireSignal — AI Recruitment Intelligence',
    '════════════════════════════════════════════════════════',
  ].join('\n')
}

export function getReportFilename(analysis: HsAnalysis): string {
  const candidate = (analysis.candidate_name || 'anonymous')
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
    .slice(0, 30)

  const role = analysis.role_title
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
    .slice(0, 30)

  const date = new Date(analysis.created_at).toISOString().slice(0, 10)

  return `hiresignal-${candidate}-${role}-${date}.txt`
}
